apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: boardgame
spec:
  selector:
    matchLabels:
      app: santa
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: santa
    spec:
      containers:
        - name: santa
          image: charifray/boardshack1:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: boardshack-ssvc
spec:
  selector:
    app: santa
  ports:
    - protocol: "TCP"
      port: 8089 # The port that the service is running on in the cluster
      targetPort: 8086 # The port exposed by the service
  type: ClusterIP # type of the service.
