# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boardgame
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: boardgame.charifcourses.me
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: boardshack-ssvc
            port:
              number: 8089

